### ISSUE TITLE
CheckList tribo A - One for All

### ISSUE THREAD

**Issue by marianamohr** [marianamohr/marianamohr#1]
### Trello

Caso você prefira usar o trello, criamos um trello que resume o checklist de conhecimentos e organização das demandas dos requisitos desse projeto.

[Link do Trello](https://trello.com/b/lFIQJbJq/mysql-one-for-all)

Como usar esse quadro?
`Mostrar menu > Mais > Copiar Quadro`

### Parte 0 - Abrir essa Issue e o PR

- [ ] Criar uma Issue para o seu usuário
- [ ] Abrir o PR

### Parte 1 - Revisão dos conteúdos e exercícios

- [ ] [21.1 - Funções mais usadas no SQL](https://app.betrybe.com/learn/course/5e938f69-6e32-43b3-9685-c936530fd326/live-lectures/62d6cebd-7e2a-4e20-ba1a-54f515407308/recording/422dcff2-63be-44b6-aecc-5aaa1b4a2b19)
- [ ] [21.2 - Descomplicando JOINs](https://app.betrybe.com/learn/course/5e938f69-6e32-43b3-9685-c936530fd326/live-lectures/62d6cebd-7e2a-4e20-ba1a-54f515407308/recording/5047f0aa-dde6-4092-9e1f-b9788ea3f8a6)
- [ ] [21.3 - Transformando ideias em um banco de dados](https://app.betrybe.com/learn/course/5e938f69-6e32-43b3-9685-c936530fd326/live-lectures/62d6cebd-7e2a-4e20-ba1a-54f515407308/recording/14e8df92-1326-43af-9e3c-1b56a11cbd8b)
- [ ] [Mentoria Estruturada - Normalização de Banco de Dados (Boteco do Seu Zé)](https://app.betrybe.com/learn/course/5e938f69-6e32-43b3-9685-c936530fd326/live-lectures/62d6cebd-7e2a-4e20-ba1a-54f515407308/recording/81429e24-e348-4fa4-8651-0418d28dc4f1)

### Parte 1.1 - Conteúdos extras

- [ ] [A tecnologia pode mudar vidas, inclusive a sua. | Hugo Santos | TEDxFortaleza - Postado por Danilo Martins](https://trybecourse.slack.com/archives/C037CH41TA7/p1663682497617589)
- [ ] [Aula Ao Vivo 3.1](https://app.betrybe.com/learn/course/5e938f69-6e32-43b3-9685-c936530fd326/live-lectures/3013dcdc-9314-44e3-8df6-8f7c37e64bcd/recording/205ddb0a-e164-4bdd-8dc3-d6e06580ddd0)
- [ ] [Aula Ao Vivo 3.2](https://app.betrybe.com/learn/course/5e938f69-6e32-43b3-9685-c936530fd326/live-lectures/3013dcdc-9314-44e3-8df6-8f7c37e64bcd/recording/afcf69c1-1d43-451e-8afc-91a3b2ea313c)
- [ ] [Aula Ao Vivo 3.3](https://app.betrybe.com/learn/course/5e938f69-6e32-43b3-9685-c936530fd326/live-lectures/3013dcdc-9314-44e3-8df6-8f7c37e64bcd/recording/1eac4507-ad10-44ce-b8dd-0548c0db43cc)
- [ ] [Materiais da Mentoria - Boteco do Seu Zé - 3.3](https://app.betrybe.com/learn/course/5e938f69-6e32-43b3-9685-c936530fd326/live-lectures/3013dcdc-9314-44e3-8df6-8f7c37e64bcd/recording/42559c74-4e87-4882-9c34-530f42bdd86c)
- [ ] [Ferramentas para modelagem do BD](https://trybecourse.slack.com/archives/C0370KS57QW/p1663877447171029)

### Parte 2 - Garantir que assimilei os seguintes conteúdos

- [ ] Como modelar um banco de dados
- [ ] Como normalizar um banco de dados
- [ ] Como criar um banco em SQL
- [ ] Como criar tabelas em SQL
- [ ] Povoar tabelas usando INSERT INTO
- [ ] Como usar funções de agregação (SUM, COUNT, MIN, MAX, AVG)
- [ ] Como usar o GROUP BY
- [ ] Como usar o GROUP BY com HAVING
- [ ] Como fazer JOINs (INNER JOIN, RIGHT JOIN, LEFT JOIN)

### Parte 3 - Resolver requisitos

Crie uma meta diária para resolução de requisitos. Um cálculo confortável é que ao fazer dois requisitos por dia (sem contar o final de semana) é possível entregar o projeto antes do prazo de mudança de turma.

**Dica 1**: O requisito 1 leva mais tempo a ser feito, reserve um dia apenas para fazer ele. 
**Dica 2**: Os requisitos 2 ao 11 tem soluções muito similares um ao outro, em quase todos você vai usar o JOIN e eventualmente o GROUP BY, mas eles são mais rápidos de se fazer. Após fazer qualquer um deles você vai ver que os demais não vão ser tão desafiadores.
**Dica 3**: Explore bem as tabelas que você construiu no requisito 1, isso vai te apoiar a saber quais tabelas serão utilizadas para fazer cada query de cada requisito.

A medida que for concluindo os requisitos vá marcando aqui qual requisito você terminou.

- [ ] Desafio 1
- [ ] Desafio 2
- [ ] Desafio 3
- [ ] Desafio 4
- [ ] Desafio 5
- [ ] Desafio 6
- [ ] Desafio 7
- [ ] Desafio 8
- [ ] Desafio 9
- [ ] Desafio 10
- [ ] Desafio 11 (Bônus)

### Parte 4 - Comemorar

🏆 Se você chegou aqui é por que concluiu mais um projeto com sucesso e virou um mestre de MySQL! Parabéns! 🏆
